@startuml

actor client as "Http Client\n<i>browser, postman, service</i>"
component tomcat as "Servlet container\n<i>tomcat, netty</i>" {
    interface http as "Http endpoint"
    component app as "Your app" {
        component servlet as "Http listener"
        component security as "Spring Security" #66c9ff
        component services as "Controllers, Services, etc"
    }
}

client --> http
http --> servlet
servlet -> security
security -> services

@enduml